# Generated by Django 3.2.25 on 2025-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
